export const CANVAS_DIMENSIONS = {
  CANVAS_WIDTH: 600,
  CANVAS_HEIGHT: 650,
};
export const LANE_WIDTH = CANVAS_DIMENSIONS.CANVAS_WIDTH / 3; 
export const PLAYER_CAR_WIDTH = 50;
export const PLAYER_CAR_HEIGHT = 100;
export const LANE_COUNT = 3;
export const OBSTACLE_CAR_WIDTH = 50;
export const OBSTACLE_CAR_HEIGHT = 100;
export const MIN_OBSTACLE_INTERVAL = 800; 
export const MAX_OBSTACLE_INTERVAL = 1500; 
export const MIN_OBSTACLE_GAP = 250;
